import os
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import requests
from data import INTERVAL_MAP
from indicators import compute_all, compute_htf
from strategy import generate_signal, Signal
from risk import position_size
from config import Config as c
from ml_model import MLFilter, extract_features
import json

BYBIT_BASE = "https://api.bybit.com/v5/market"
DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "historical_data")

class BacktestEngine:
    """
    Backtests the algo trading bot on historical data.
    Reads from local CSV files (generated by fetch_history.py).
    Falls back to Bybit API if CSV not found.
    """
    
    def __init__(self, symbols=None, start_date=None, balance=1000, days=180):
        self.symbols = symbols or c.SYMBOLS
        self.balance = balance
        self.days = days
        self.start_date = start_date or (datetime.now() - timedelta(days=days))
        self.trades = []
        self.equity_curve = []

    def load_from_csv(self, symbol: str, interval: str = "15m") -> pd.DataFrame:
        """
        Load historical data from local CSV file.
        Returns empty DataFrame if file not found.
        """
        filename = f"{symbol}_{interval}.csv"
        filepath = os.path.join(DATA_DIR, filename)
        
        if not os.path.exists(filepath):
            return pd.DataFrame()
        
        df = pd.read_csv(filepath)
        df["timestamp"] = pd.to_datetime(df["timestamp"])
        for col in ["open", "high", "low", "close", "volume"]:
            df[col] = df[col].astype(float)
        
        # Filter to requested date range
        start_ts = pd.Timestamp(self.start_date)
        df = df[df["timestamp"] >= start_ts].reset_index(drop=True)
        
        return df
        
    def fetch_historical_data(self, symbol, interval="15m", days=30):
        """
        Fetch 1 month of historical 15m candles from Bybit.
        Returns dataframe sorted by timestamp.
        """
        bybit_interval = INTERVAL_MAP.get(interval, "15")
        all_candles = []
        current_date = datetime.now()
        
        # Bybit API limits to ~200 candles per request
        # We need to fetch multiple batches
        while len(all_candles) < (days * 24 * 60 // 15):  # 15m candles in 1 month
            try:
                url = f"{BYBIT_BASE}/kline"
                params = {
                    "category": "linear",
                    "symbol": symbol,
                    "interval": bybit_interval,
                    "limit": 200,
                    "end": int(current_date.timestamp() * 1000)
                }
                resp = requests.get(url, params=params, timeout=10)
                resp.raise_for_status()
                
                raw = resp.json()
                if raw.get("retCode") != 0:
                    print(f"Bybit error: {raw.get('retMsg')}")
                    break
                
                candles = raw["result"]["list"]
                if not candles:
                    break
                
                all_candles.extend(candles)
                
                # Move back to the timestamp of the oldest candle
                oldest_timestamp = float(candles[-1][0])
                current_date = datetime.fromtimestamp(oldest_timestamp / 1000)
                
                # Stop if we've gone back days+ days
                if (datetime.now() - current_date).days >= days:
                    break
                    
            except Exception as e:
                print(f"Error fetching {symbol}: {e}")
                break
        
        # Convert to DataFrame
        df = pd.DataFrame(all_candles, columns=[
            "timestamp", "open", "high", "low", "close", "volume", "turnover"
        ])
        df["timestamp"] = pd.to_datetime(df["timestamp"].astype(float), unit="ms")
        for col in ["open", "high", "low", "close", "volume"]:
            df[col] = df[col].astype(float)
        
        df = df.sort_values("timestamp").reset_index(drop=True)
        return df[["timestamp", "open", "high", "low", "close", "volume"]]
    
    def run_backtest(self):
        """
        v9 Backtest: 4H Trend Rider with Daily bias.
        Loads 15m data → resamples to 4H for signals, 1D for trend bias.
        Exit: Hard SL + Hard TP (fixed, no trailing).
        """
        print(f"\n{'='*70}")
        print(f"  BACKTESTING ALGO BOT v9 — 4H TREND RIDER — {self.days} DAYS")
        print(f"  Start Balance: ${self.balance:.2f}")
        print(f"  Symbols: {len(self.symbols)}")
        print(f"  Primary: 4H | HTF: Daily | SL: {c.SL_ATR_MULT:.1f} ATR | TP: {c.TP_ATR_MULT:.1f} ATR (R:R 1:{c.TP_ATR_MULT/c.SL_ATR_MULT:.1f})")
        print(f"{'='*70}\n")
        
        # Load 15m data for all symbols (will be resampled)
        all_data_15m = {}
        for symbol in self.symbols:
            print(f"   {symbol}...", end=" ", flush=True)
            try:
                df = self.load_from_csv(symbol, "15m")
                if not df.empty:
                    print(f"CSV ({len(df)} 15m candles)", end="")
                else:
                    print("CSV not found, fetching from API...", end=" ", flush=True)
                    df = self.fetch_historical_data(symbol, interval="15m", days=self.days)
                    print(f"API ({len(df)} 15m candles)", end="")
                
                if not df.empty:
                    all_data_15m[symbol] = df
                    print(" ✓")
                else:
                    print(" ✗ no data")
            except Exception as e:
                print(f" ✗ {e}")
        
        if not all_data_15m:
            print("No data fetched. Aborting.")
            return
        
        # Resample 15m → 4H for primary signals
        print("\n Resampling 15m → 4H...")
        all_data_4h = {}
        for symbol, df in all_data_15m.items():
            ohlcv = df[["timestamp", "open", "high", "low", "close", "volume"]].copy()
            ohlcv = ohlcv.set_index("timestamp")
            resampled = ohlcv.resample("4h").agg({
                "open": "first",
                "high": "max",
                "low": "min",
                "close": "last",
                "volume": "sum"
            }).dropna()
            if len(resampled) >= 100:
                all_data_4h[symbol] = resampled
                print(f"   {symbol}: {len(resampled)} 4H candles")
            else:
                print(f"   {symbol}: ⚠ Only {len(resampled)} 4H candles (need 100+)")
        
        if not all_data_4h:
            print("No symbols have enough 4H data. Aborting.")
            return
        
        # Find common date range — only include symbols with enough coverage
        target_start = pd.Timestamp(self.start_date)
        qualified_symbols = []
        for symbol, df in all_data_4h.items():
            if df.index.min() <= target_start + timedelta(days=7):
                qualified_symbols.append(symbol)
            else:
                print(f"   ⚠ {symbol}: data starts {df.index.min().date()}, skipping (need {target_start.date()})")
        
        # Remove unqualified symbols
        for symbol in list(all_data_4h.keys()):
            if symbol not in qualified_symbols:
                del all_data_4h[symbol]
        
        if not all_data_4h:
            print("No symbols have enough data for the requested period. Aborting.")
            return
        
        min_date = max([df.index.min() for df in all_data_4h.values()])
        max_date = min([df.index.max() for df in all_data_4h.values()])
        
        print(f"\n Backtest period: {min_date.date()} to {max_date.date()}")
        print(f"   Duration: {(max_date - min_date).days} days")
        print(f"   Symbols ({len(all_data_4h)}): {', '.join(all_data_4h.keys())}")
        
        # Trim to common range
        for symbol in list(all_data_4h.keys()):
            df = all_data_4h[symbol]
            all_data_4h[symbol] = df[(df.index >= min_date) & (df.index <= max_date)]
        
        # Compute indicators on 4H data
        print("\n Computing 4H indicators...")
        all_indicators = {}
        for symbol, df in all_data_4h.items():
            indicators_df = compute_all(df)
            indicators_df = indicators_df.reset_index()
            indicators_df.rename(columns={"index": "timestamp"}, inplace=True)
            all_indicators[symbol] = indicators_df
            print(f"   {symbol}: {len(indicators_df)} candles with indicators")
        
        # Compute Daily HTF from 15m data
        print("\n Computing Daily HTF trend...")
        all_htf = {}
        for symbol, df in all_data_15m.items():
            if symbol not in all_data_4h:
                continue
            ohlcv = df[["timestamp", "open", "high", "low", "close", "volume"]].copy()
            htf = compute_htf(ohlcv, "1D")
            if not htf.empty:
                all_htf[symbol] = htf
                print(f"   {symbol}: {len(htf)} daily candles")
            else:
                print(f"   {symbol}: insufficient data for daily HTF")
        
        # ── SIMULATION ────────────────────────────────────────────
        current_balance = self.balance
        open_positions = []
        daily_pnl = 0.0
        daily_trades = 0
        last_daily_reset = min_date.date()
        last_trade_idx = -999
        symbols_in_position = set()
        consecutive_losses = 0
        symbol_cooldown = {}  # {symbol: candle_num when cooldown expires}
        
        # ML Filter — walk-forward
        ml_filter = MLFilter(confidence_threshold=0.55)
        ml_blocked = 0
        ml_passed = 0
        pending_ml_features = {}  # {position_id: features_dict}
        
        # Use first symbol's timestamps as master
        master_symbol = list(all_indicators.keys())[0]
        master_timestamps = all_indicators[master_symbol]["timestamp"].values
        total_candles = len(master_timestamps)
        
        # Build index maps for fast lookup
        symbol_idx_maps = {}
        for symbol, df in all_indicators.items():
            ts_array = df["timestamp"].values
            symbol_idx_maps[symbol] = {ts: i for i, ts in enumerate(ts_array)}
        
        print(f"\n Running simulation on {total_candles} 4H candles...\n")
        
        trades_count = 0
        
        for candle_num, ts in enumerate(master_timestamps):
            current_date = pd.Timestamp(ts).date()
            
            # ── Daily reset ────────────────────────────────────────
            if current_date != last_daily_reset:
                daily_pnl = 0.0
                daily_trades = 0
                last_daily_reset = current_date
            
            # ── Daily loss guard ───────────────────────────────────
            if not self._daily_limit_ok(daily_pnl, current_balance):
                continue
            
            # ══════════════════════════════════════════════════════════
            # EXIT LOGIC — Fixed SL + Fixed TP. No trailing.
            # ══════════════════════════════════════════════════════════
            closed_indices = []
            for i, pos in enumerate(open_positions):
                sym = pos["symbol"]
                if sym not in symbol_idx_maps or ts not in symbol_idx_maps[sym]:
                    continue
                
                row_idx = symbol_idx_maps[sym][ts]
                row = all_indicators[sym].iloc[row_idx]
                
                high = float(row["high"])
                low = float(row["low"])
                
                exit_price = None
                exit_reason = None
                
                # ── CHECK SL/TP ───────────────────────────────────
                if pos["direction"] == Signal.LONG:
                    if low <= pos["sl"]:
                        exit_price = pos["sl"]
                        exit_reason = "STOPLOSS"
                    elif high >= pos["tp"]:
                        exit_price = pos["tp"]
                        exit_reason = "TAKEPROFIT"
                else:
                    if high >= pos["sl"]:
                        exit_price = pos["sl"]
                        exit_reason = "STOPLOSS"
                    elif low <= pos["tp"]:
                        exit_price = pos["tp"]
                        exit_reason = "TAKEPROFIT"
                
                # ── RECORD EXIT ───────────────────────────────────
                if exit_price:
                    if pos["direction"] == Signal.LONG:
                        pnl = (exit_price - pos["entry_price"]) * pos["qty"]
                    else:
                        pnl = (pos["entry_price"] - exit_price) * pos["qty"]
                    
                    current_balance += pnl
                    daily_pnl += pnl
                    
                    # Track consecutive losses
                    if pnl < 0:
                        consecutive_losses += 1
                        # Per-symbol cooldown: 6 candles (24h) after SL
                        symbol_cooldown[sym] = candle_num + 6
                    else:
                        consecutive_losses = 0
                    
                    # ML feedback — record trade result for training
                    pos_id = pos.get("pos_id")
                    if pos_id and pos_id in pending_ml_features:
                        ml_filter.add_completed_trade(
                            pending_ml_features[pos_id],
                            won=(pnl > 0)
                        )
                        del pending_ml_features[pos_id]
                    
                    self.trades.append({
                        "symbol": sym,
                        "direction": pos["direction"],
                        "entry_time": pos["entry_time"],
                        "entry_price": pos["entry_price"],
                        "exit_time": pd.Timestamp(ts),
                        "exit_price": exit_price,
                        "qty": pos["qty"],
                        "pnl": pnl,
                        "pnl_pct": (pnl / (pos["entry_price"] * pos["qty"])) * 100,
                        "reason": exit_reason
                    })
                    
                    icon = "✅" if pnl > 0 else "❌"
                    print(f"[{pd.Timestamp(ts)}] {icon} {sym} {pos['direction']} | "
                          f"${pos['entry_price']:.2f}→${exit_price:.2f} | "
                          f"P&L: ${pnl:+.2f} ({exit_reason})")
                    
                    closed_indices.append(i)
                    symbols_in_position.discard(sym)
                    last_trade_idx = candle_num
                    trades_count += 1
            
            # Remove closed positions
            for i in sorted(closed_indices, reverse=True):
                open_positions.pop(i)
            
            # ══════════════════════════════════════════════════════════
            # ENTRY LOGIC — With HTF bias
            # ══════════════════════════════════════════════════════════
            if len(open_positions) < c.MAX_POSITIONS:
                if (candle_num - last_trade_idx) >= c.MIN_CANDLES_SINCE_TRADE:
                    # Daily trade cap
                    if daily_trades >= c.MAX_TRADES_PER_DAY:
                        pass  # Skip entry this candle
                    # Consecutive loss cooldown
                    elif consecutive_losses >= c.MAX_CONSECUTIVE_LOSSES:
                        if (candle_num - last_trade_idx) < c.LOSS_COOLDOWN_CANDLES * 2:
                            pass  # Extended cooldown after losing streak
                        else:
                            consecutive_losses = 0  # Reset after extended cooldown
                    else:
                      for symbol in all_data_4h.keys():
                        if symbol in symbols_in_position:
                            continue
                        if len(open_positions) >= c.MAX_POSITIONS:
                            break
                        # Per-symbol cooldown check
                        if symbol in symbol_cooldown and candle_num < symbol_cooldown[symbol]:
                            continue
                        if symbol not in symbol_idx_maps:
                            continue
                        if ts not in symbol_idx_maps[symbol]:
                            continue
                        
                        row_idx = symbol_idx_maps[symbol][ts]
                        if row_idx < 50:
                            continue
                        
                        # Get HTF bias for this symbol
                        htf_bias = self._get_htf_bias(symbol, ts, all_htf)
                        
                        # Get signal from strategy
                        hist_start = max(0, row_idx - 99)
                        hist_df = all_indicators[symbol].iloc[hist_start:row_idx + 1].copy()
                        signal_df = hist_df.drop(columns=["timestamp"])
                        
                        try:
                            signal, sl, tp = generate_signal(signal_df, htf_bias)
                            
                            if signal != Signal.NONE:
                                entry_price = float(signal_df.iloc[-1]["close"])
                                entry_atr = float(signal_df.iloc[-1]["atr"])
                                
                                # ML Filter — extract features and check confidence
                                curr_row = signal_df.iloc[-1]
                                prev_row = signal_df.iloc[-2]
                                ml_features = extract_features(curr_row, prev_row, entry_price, entry_atr, signal)
                                should_take, ml_conf, ml_sl_mult, ml_tp_r = ml_filter.should_take_trade(ml_features)
                                
                                if not should_take:
                                    ml_blocked += 1
                                    continue
                                ml_passed += 1
                                
                                # Use ML-predicted SL/TP if model is trained
                                if ml_filter.is_trained:
                                    sl_dist = entry_atr * ml_sl_mult
                                    if signal == Signal.LONG:
                                        sl = entry_price - sl_dist
                                        tp = entry_price + sl_dist * ml_tp_r
                                    else:
                                        sl = entry_price + sl_dist
                                        tp = entry_price - sl_dist * ml_tp_r
                                
                                qty = position_size(current_balance, entry_price, sl, symbol)
                                
                                if qty > 0:
                                    lev = c.SYMBOL_LEVERAGE.get(symbol, c.LEVERAGE)
                                    orig_sl_dist = abs(entry_price - sl)
                                    
                                    pos_id = f"{symbol}_{candle_num}"
                                    pending_ml_features[pos_id] = ml_features
                                    
                                    new_pos = {
                                        "symbol": symbol,
                                        "direction": signal,
                                        "entry_price": entry_price,
                                        "qty": qty,
                                        "sl": sl,
                                        "tp": tp,
                                        "atr": entry_atr,
                                        "orig_sl_dist": orig_sl_dist,
                                        "entry_time": pd.Timestamp(ts),
                                        "entry_candle": candle_num,
                                        "leverage": lev,
                                        "pos_id": pos_id,
                                        "ml_conf": ml_conf
                                    }
                                    open_positions.append(new_pos)
                                    symbols_in_position.add(symbol)
                                    last_trade_idx = candle_num
                                    daily_trades += 1
                                    
                                    sl_dist = abs(entry_price - sl)
                                    r_ratio = abs(tp - entry_price) / sl_dist if sl_dist > 0 else 0
                                    ml_tag = f" | ML:{ml_conf:.0%}" if ml_filter.is_trained else ""
                                    print(f"[{pd.Timestamp(ts)}] 🟢 {symbol} {signal} @ "
                                          f"${entry_price:.2f} | SL: ${sl:.2f} | "
                                          f"TP: ${tp:.2f} | R:R 1:{r_ratio:.1f} | "
                                          f"HTF: {htf_bias or 'NEUTRAL'}{ml_tag}")
                        
                        except Exception:
                            continue
            
            # ── Record equity ─────────────────────────────────────
            if candle_num % 10 == 0:
                self.equity_curve.append({
                    "timestamp": pd.Timestamp(ts),
                    "balance": current_balance,
                    "open_positions": len(open_positions)
                })
            
            # Progress
            if candle_num % 2000 == 0 and candle_num > 0:
                pct = (candle_num / total_candles) * 100
                print(f"   ... {pct:.0f}% complete | Trades: {trades_count} | Balance: ${current_balance:.2f}")
        
        # Close remaining positions
        for pos in open_positions:
            last_price = float(all_data_4h[pos["symbol"]].iloc[-1]["close"])
            if pos["direction"] == Signal.LONG:
                pnl = (last_price - pos["entry_price"]) * pos["qty"]
            else:
                pnl = (pos["entry_price"] - last_price) * pos["qty"]
            current_balance += pnl
            self.trades.append({
                "symbol": pos["symbol"],
                "direction": pos["direction"],
                "entry_time": pos["entry_time"],
                "entry_price": pos["entry_price"],
                "exit_time": max_date,
                "exit_price": last_price,
                "qty": pos["qty"],
                "pnl": pnl,
                "pnl_pct": (pnl / (pos["entry_price"] * pos["qty"])) * 100,
                "reason": "BACKTEST_END"
            })
        
        self.print_results(current_balance, self.balance, ml_filter, ml_passed, ml_blocked)
    
    def _get_htf_bias(self, symbol: str, ts, all_htf: dict) -> str:
        """
        Get Daily trend bias for the given timestamp.
        Returns "LONG", "SHORT", or None (neutral).
        """
        if symbol not in all_htf:
            return None
        
        htf = all_htf[symbol]
        ts_pd = pd.Timestamp(ts)
        
        # Find the most recent HTF candle before this timestamp
        htf_before = htf[htf.index <= ts_pd]
        if htf_before.empty:
            return None
        
        last_htf = htf_before.iloc[-1]
        
        if bool(last_htf.get("trend_up", False)):
            return "LONG"
        elif bool(last_htf.get("trend_down", False)):
            return "SHORT"
        return None
    
    def _daily_limit_ok(self, daily_pnl: float, balance: float) -> bool:
        """Check daily loss limit"""
        if balance == 0:
            return True
        return (daily_pnl / balance) > -c.DAILY_LOSS_LIMIT
    
    def print_results(self, final_balance, initial_balance, ml_filter=None, ml_passed=0, ml_blocked=0):
        """
        Print backtest summary statistics.
        """
        if not self.trades:
            print("\n❌ No trades executed during backtest.")
            return
        
        df_trades = pd.DataFrame(self.trades)
        
        total_pnl = final_balance - initial_balance
        total_return_pct = (total_pnl / initial_balance) * 100
        
        winning_trades = df_trades[df_trades["pnl"] > 0]
        losing_trades = df_trades[df_trades["pnl"] < 0]
        
        win_rate = (len(winning_trades) / len(df_trades)) * 100 if len(df_trades) > 0 else 0
        avg_win = winning_trades["pnl"].mean() if len(winning_trades) > 0 else 0
        avg_loss = abs(losing_trades["pnl"].mean()) if len(losing_trades) > 0 else 0
        profit_factor = (winning_trades["pnl"].sum() / abs(losing_trades["pnl"].sum())) if len(losing_trades) > 0 and losing_trades["pnl"].sum() != 0 else 0
        
        equity_df = pd.DataFrame(self.equity_curve)
        max_balance = equity_df["balance"].max()
        max_drawdown = ((max_balance - equity_df["balance"].min()) / max_balance) * 100 if max_balance > 0 else 0
        
        print(f"\n{'='*70}")
        print(f"  BACKTEST RESULTS — {self.days} DAYS")
        print(f"{'='*70}")
        print(f"  Initial Balance:     ${initial_balance:.2f}")
        print(f"  Final Balance:       ${final_balance:.2f}")
        print(f"  Total P&L:           ${total_pnl:+.2f}")
        print(f"  Total Return:        {total_return_pct:+.2f}%")
        print(f"\n  Total Trades:        {len(df_trades)}")
        print(f"  Winning Trades:      {len(winning_trades)} ({win_rate:.1f}%)")
        print(f"  Losing Trades:       {len(losing_trades)} ({100-win_rate:.1f}%)")
        print(f"\n  Avg Win:             ${avg_win:+.2f}")
        print(f"  Avg Loss:            ${avg_loss:+.2f}")
        print(f"  Profit Factor:       {profit_factor:.2f} (>1.5 is excellent)")
        print(f"  Max Drawdown:        {max_drawdown:.2f}%")
        print(f"{'='*70}\n")
        
        # Show trades table
        print("📋 All Trades:")
        print(df_trades[["symbol", "direction", "entry_price", "exit_price", "pnl", "pnl_pct", "reason"]].to_string())
        
        # ML Stats
        print(f"\n🤖 ML Filter Stats:")
        print(f"   Signals passed: {ml_passed}")
        print(f"   Signals blocked: {ml_blocked}")
        if ml_passed + ml_blocked > 0:
            print(f"   Block rate: {ml_blocked / (ml_passed + ml_blocked):.1%}")
        if ml_filter and ml_filter.is_trained:
            print(f"   Training samples: {len(ml_filter.training_labels)}")
            importances = ml_filter.get_feature_importance()
            print(f"   Top features: {list(importances.keys())[:5]}")
            ml_filter.save("ml_filter.pkl")
            print(f"   Model saved to ml_filter.pkl")
        
        # Save results to CSV
        df_trades.to_csv("backtest_trades.csv", index=False)
        equity_df.to_csv("backtest_equity_curve.csv", index=False)
        print("\n✅ Results saved to backtest_trades.csv and backtest_equity_curve.csv")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Run backtest on historical data")
    parser.add_argument("--days", type=int, default=180, help="Days to backtest (default: 180)")
    parser.add_argument("--balance", type=float, default=1000, help="Starting balance (default: 1000)")
    parser.add_argument("--symbol", type=str, default=None, help="Single symbol to backtest (default: all)")
    args = parser.parse_args()
    
    symbols = [args.symbol] if args.symbol else None
    backtester = BacktestEngine(symbols=symbols, balance=args.balance, days=args.days)
    backtester.run_backtest()
